### ISSUE TITLE
[Dataset] 문제5 데이터셋 메타정보 제공 문의

### ISSUE THREAD

**Issue by 21jun** [hunminjeongeum-competition-final-2021/Speech-to-Text#1]
# 주제
- 음성인식 (문제5 방언데이터셋)

# 상황 (자세히 작성해주시면 좋습니다.)

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)

- train, test 셋의 json 정보가 어디까지 제공되는지 궁금합니다.
가령 이번 문제의 데이터셋은 한 파일의 길이가 매우 긴 형태인데 (1000~2000초 이상) json 파일에 명시된 음성 시작,끝 정보가
train, test 셋에 모두 제공되는지 궁금합니다.

예륻들어 (aihub에서 다운받은 데이터셋 예시)
```json
 "id": "DKCI20000001.1.1.1",
  "form": "자 음식을 멀 좋아하느냐 하면은",
  "standard_form": "자 음식을 멀 좋아하느냐 하면은",
  "dialect_form": "자 음식을 멀 좋아하느냐 하면은",
  "speaker_id": "----",
  "start": 0.01,
  "end": 3.45,
  "note": "",
...
...
 "id": "DKCI20000001.1.1.392",
  "form": "음식에 관련된 이야기를 이때까지 나눠봤습니다.",
  "standard_form": "음식에 관련된 이야기를 이때까지 나눠봤습니다.",
  "dialect_form": "음식에 관련된 이야기를 이때까지 나눠봤습니다.",
  "speaker_id": "CI0216",
  "start": 1793.31,
  "end": 1797.44,
  "note": "",
```
위와같이 각 발화의 메타정보에 start, end (발화의 시작과 끝점)가 제공됩니다. 

README 에 작성된 설명을 보면, 

### Test Dataset

- `root_path/test/test_data/`(60개의 wav 파일 \*확장자 없는 레이블 형태)

  ```
  DJDD20000306
  DJDD20000307
  ...
  DKSR20006835
  DKSR20006836
  ```

### Test Label

- `root_path/test/test_label` (참가자 접근 불가)

- `test_label (DataFrame 형식, 60 rows)`

  - columns = `["file_name", "text"]`

  - `file_name` - test_data 폴더에 존재하는 wav파일명 (ex. DJDD20000306)

  - `text` - test_data 폴더에 존재하는 wav파일과 매칭되는 Text 정보 (json 파일의 `dialect_form`을 ' '로 이어붙여 생성하였음)

----

위처럼 명시되어 있는데, 이 경우 테스트셋에는 위 json 예시처럼 발화의 시작과 끝 정보(start, end)가 제공되지 않는것 인가요?

또한 학습을 위해서라도 train셋에도 위와 같은 start, end 정보가 필요하다고 생각됩니다.

----
ex)
제공되는 정보
DKCI20000001 (음성파일)
DKCI20000001.json (id, start, end 만 남긴 메타정보)

제출
columns = [`"file_name"`,` "text"`]
`file_name`: DKCI20000001
`text`: DKCI20000001.1.1.1 ~ DKCI20000001.1.1.392 까지의 발화를 ' '로 이어붙인 문자열

----

아직 대회가 시작되지 않아, readme에 관련 내용이 업데이트 되지 않은 것 같지만, 혹시 몰라 문의드립니다. 감사합니다.

**Comment by DaconHoneyBee** [comment]
안녕하세요!

말씀해주신대로 대화의 시작지점 및 끝지점 정보를 포함하여
aihub에서 제공된 메타데이터 전체를 제공할 예정입니다.

대회 시작전에 README.md 파일 업데이트될 예정입니다.

감사합니다.

2021년 10월 30일 (토) 오후 5:24, lee1jun ***@***.***>님이 작성:

**Comment by DaconHoneyBee** [comment]
@21jun 님 안녕하세요!

말씀해주신대로 대화의 시작지점 및 끝지점 정보를 포함하여
aihub에서 제공된 메타데이터 전체를 제공할 예정입니다.

대회 시작전에 README.md 파일 업데이트될 예정입니다.

감사합니다.

**Comment by 21jun** [comment]
@DaconHoneyBee 감사합니다.

업데이트된 내용을 보니, 학습셋에는 info 정보가 제공되는데, 
`root_path/train/train_data/info(1,059개의 json 파일 *확장자 없는 레이블 형태)`

테스트셋에는 위와같은 대화의 시작지점 및 끝지점 정보를 제공하지 않는것인가요?
(테스트셋에는 다른 정보를 제거하고 id, start, end 정보만이 주어져야 한다고 생각됩니다)

`root_path/test/test_data/wav`
`root_path/test/test_data/info` 등

**Comment by DaconHoneyBee** [comment]
@21jun test_data는 wav파일만 제공됩니다. 
test_label은 발화 별로 나뉘어있지 않고,
한 대화 내의 모든 발화를 띄어쓰기 단위로 이어붙인 형태로 구성되어있습니다.
따라서 발화 시작 지점, 종료 지점과 상관없이 전체 대화를 추론해주시면 됩니다.

**Comment by 21jun** [comment]
@DaconHoneyBee 안녕하세요. 확인 감사합니다.

다만, 테스트셋의 2000초 가량의 단일 음성 파일을 한번에 추론하는것은 가용 메모리의 한계/성능 하락 문제로 매우 어려울 것으로 예상됩니다.

학습셋에는 발화별 시작, 끝 정보가 주어지지만, 테스트셋에만 주어지지 않는것도 납득하기가 어렵습니다.
(학습시에도 2000초 가량의 음성을 한번에 학습하는것이 아닌 시작,끝 정보를 이용해 10초내외의 음성을 학습하게 될 것 (GPU메모리상문제 + 데이터의 특성상 여려명의 화자가 등장함))

만약 한 파일당 2000초 가량의 테스트셋을 발화별 시작,끝 정보가 없이 한번에 추론해야 한다면, 문제 범위를 벗어나는것이 아닐지 여쭤봅니다. (화자 인식/분리 등의 작업이 별도로 필요할 수 있음)

문제3, 문제4 와 같이 이미 발화별로 테스트셋이 나눠져있는 경우는 이러한 문제가 발생하지 않지만, 문제5의 경우 AIHUB의 데이터 구성 방식(시작, 끝지점으로 발화구분)이 다른 두 문제와 달라 발생한 문제라고 생각됩니다. 이러한 경우엔 테스트셋에도 발화의 시작, 끝 정보들을 제공해주셔야 정상적으로 진행이 가능하다고 생각합니다.
(test_label 은 지금과 같은 형식이돼, wav 파일을 쪼개어 추론하고 이를 어이붙여 제출할 수 있도록 발화 시작, 끝 지점들이 제공될 필요가 있음)

문제의 출제의도가 이와같은 것인지 혹은 테스트셋에도 발화의 시작,끝 지점을 제공해주실수 있을지 여쭤봅니다.

감사합니다.

**Comment by DaconHoneyBee** [comment]
@21jun 발화별로 나눠서 접근하는 경우, 시작 지점과 끝 지점으로 발화를 구분하는 task까지 문제 출제의도에 포함됩니다. 
본 대회의 음성인식 분야는 외부데이터 및 pre-trained 모델을 허용하고 있기 때문에 본선 난이도를 높이기 위해 위와 같이 문제를 구성하였습니다.

**Comment by 21jun** [comment]
@DaconHoneyBee 답변 감사드립니다.

말씀주신 방법대로 수행하겠습니다. 감사합니다.
