### ISSUE TITLE
[Dataset] final_stt_1 텍스트 라벨 문의

### ISSUE THREAD

**Issue by Choiuijin1125** [hunminjeongeum-competition-final-2021/Speech-to-Text#10]
# 주제
- `final_stt_1` 데이터에 일부 전사가 잘 되지 않은 데이터들이 학습용 텍스트로 포함되어 있는 것 같아 문의 드립니다.

# 상황 (자세히 작성해주시면 좋습니다.)
- 아래 이미지와 같이 영문, 간투어 등이 나올 경우 (SN:) 같은 Symbolic 단어들이 학습용 데이터에 포함되어 있음.
-  ex) (NO:), (SP:), (SN:) (FP:) 등

![image](https://user-images.githubusercontent.com/32811094/140069404-56023f1f-e666-405c-b809-7d2f97ac0f35.png)
 
![image](https://user-images.githubusercontent.com/32811094/140069927-39138d13-1691-44ed-a925-d40e86f06af8.png)

**Comment by dacon-murdoch** [comment]
안녕하세요 :)

test data에 대한 설명을 드릴 수는 없으나
train data에서 말씀하신 Symbolic 단어들을 제거하신 후 모델 학습을 진행하시면 되겠습니다.

감사합니다.

**Comment by Choiuijin1125** [comment]
네 확인했습니다. 감사합니다. :)
