### ISSUE TITLE
[대회 진행 관련 문의] 개인 인프라 활용 관련 문의

### ISSUE THREAD

**Issue by Ldoun** [hunminjeongeum-competition-final-2021/Speech-to-Text#11]
# 주제
- 개인 인프라 활용 관련 문의
# 내용
-  대회 규정에 참가팀이 보유한 인프라를 활용할 수 있는 것으로 알고 있습니다. 이렇게 진행할 때는 AI-hub에서 데이터를 다운로드 받은 후 사용하면 되나요? 아니면 NSML의 train 데이터를 다운 받을 수 있는 방법이 있나요?  
AI-hub데이터를 사용하면 nsml의 test set과 중복되는 data로 학습시키는 것이 아닌가 하는 의문이 들어 문의 드립니다.

**Comment by DaconHoneyBee** [comment]
@Ldoun 안녕하세요.
NSML을 통해 train 데이터를 다운받을 수는 없고, AI-Hub에서 관련 데이터를 다운받아 사용하실 수 있습니다.
본선에 사용된 test set은 AI-Hub에 업로드되어 있지 않은 데이터를 사용했기 때문에,
test set이 학습에 사용될 걱정은 안하셔도 됩니다.
감사합니다.
