### ISSUE TITLE
[대회 진행 관련 문의] 팀별 활동 동영상 제출 

### ISSUE THREAD

**Issue by 21jun** [hunminjeongeum-competition-final-2021/Speech-to-Text#12]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/29483429/140885148-875fd74d-eebf-477e-a2ff-7b04e19c0646.png">

대회일정상 11/8 팀별 활동 동영상 제출이 있는데, 이전 팀 소개 PPT처럼 따로 메일로 안내 받지는 못했습니다.

해당 활동 동영상은 제출하지 않아도 되는것인가요?

**Comment by dukuaris** [comment]
안녕하세요 경진대회 운영사무국입니다. 활동 동영상 제출은 일정이 다소 연기되어 며칠내로 메일로 공지드리겠습니다. 먼저 확인해 주셔서 감사합니다.
