### ISSUE TITLE
[NSML] GPU 자원량 확인

### ISSUE THREAD

**Issue by kaen2891** [hunminjeongeum-competition-final-2021/Speech-to-Text#13]
# 주제
- GPU 확인량 부탁드립니다.

# 상황 (자세히 작성해주시면 좋습니다.)
- 아무것도 돌리지 않는 상황에서 gpu session이 1개밖에 안돌아가는 것 같습니다. 예선전에도 같은 문제가 발생했는데 확인 부탁드려도 될까요?

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 사용자 세션 정보: 
- Session ID: nia1009
- 팀명: 크누보이스
- CLI 에러 (CLI 에러가 아닌 경우 제거)
   ```shell
   # 이곳에 에러 메세지를 넣어주세요
   $ test
   ```

![image](https://user-images.githubusercontent.com/46586785/141260636-8f99fde9-c3e7-44fb-a789-19e665744472.png)

![image](https://user-images.githubusercontent.com/46586785/141260652-3c64cbae-f5f8-49db-83b6-77d5c1d6e374.png)

- 웹 UI 에러 이미지
 // 이곳에 에러 이미지를 추가해주세요

# 기타 문의 사항
- @bluebrush 님 확인 부탁드립니다.

**Comment by kaen2891** [comment]
혹시 프로그램을 제가 --memory 100G를 2번 연속해서 안되는 것일까요?

명령어 실행 후 5분이 기다려야 가능합니다.

submit test는 가능한데 main이 안되는 것 같아서 맞는 문제인 것 같은데 확인 부탁드려도 될까요?

**Comment by bluebrush** [comment]
해당 노드 리부팅한번 하겠습니다. (현재 돌고 있는 세션은 없는 것으로 확인되었습니다. )

**Comment by bluebrush** [comment]
@kaen2891 님. 

점검 완료되었습니다. 
잔여 GPU 정상 출력되고 있습니다. 
```
 nsml status -r -v
Your realm : speech04
GPU Model : Tesla V100-PCIE-32GB
The total number of available GPUs: 2/2
The total number of available CPUs: 16/16
```

**Comment by kaen2891** [comment]
감사합니다.
