### ISSUE TITLE
[대회 진행 관련 문의] 제출 시 CER 관련 정보 제공 가능할까요?

### ISSUE THREAD

**Issue by senti-mkyu** [hunminjeongeum-competition-final-2021/Speech-to-Text#15]
# 주제
- 제출 시 CER 정보 제공 가능할까요?

# 상황 (자세히 작성해주시면 좋습니다.)
- 

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- CER 계산할 때 대치/삽입/삭제 에러로 계산할텐데 관련 정보를 score print할 때 같이 출력해주실 수 없을까요?
- 왜냐하면, 방언3이 20여 분 길이의 통파일이라 EPD 등 segmentation을 진행해야하는데, CER 값 만으로는 이게 segmentation이 너무 마진이 넓은지, 혹은 누락이 발생하는지 알 수가 없어서 어느 방향으로 개선해야할지..

# 기타 문의 사항
- 대회 운영에 노고가 많으십니다 :)

**Comment by DaconHoneyBee** [comment]
@aod1310 안녕하세요.
말씀 주신 내용과 관련하여 내부적으로 검토중입니다.
최대한 빨리 답변 드릴 수 있도록 하겠습니다.
감사합니다.

**Comment by senti-mkyu** [comment]
추가로 CER을 계산하는 방식이 어떤지 궁금합니다.
제공되는 데이터의 음성 길이가 대략 20분정도라고 할 때, 보통 문자 수가 5000개 이상 정도로 파악됩니다.
이때 전사문과 인식결과의 CER 계산을 위해 Full-Search하게될 경우 연산시간이 굉장히 길어질텐데, nsml평가시스템은 CER 결과가 생각보다 빠르게 나오는 것 같습니다.
Full-Search의 연산시간이 크게 발생함에 따라 Search Space 크게 손해보지 않는 선에서 제한하여 연산속도를 빠르게 하는 경우가 있는데, 저희가 추정하기로는 nsml평가시스템이 full-search로 계산하지 않는 것 같다는 추측을 하고 있습니다.
search space를 제한하는 경우 insertion 등 에러로 align이 밀리게 되면 왕창 틀리게 결과가 나오기도 한데
nsml 평가는 어떤식으로 평가되고 있는지 궁금합니다.

**Comment by DaconHoneyBee** [comment]
@aod1310  
submit 과정에서 대치/삽입/삭제 관련 정보를 출력하는 것은 evaluation.py 변경 및 리더보드 초기화 문제를 발생시켜 도움 드리기 어려울 것 같습니다.
CER 계산은 Full-Search가 아닌 방식으로 Levenshtein distance를 사용하여 계산하고 있습니다.

**Comment by senti-mkyu** [comment]
@DaconHoneyBee 
안녕하세요,
리더보드의 성능들이 저희 포함 다들 저조한 상태인데, AIhub에서 방언데이터를 모두 받아 각 지역별로 12개씩 랜덤 샘플링(총 60개 샘플링)하여
몇 번 같은 EPD, 같은 AM으로 평가해도 리더보드의 결과보다 훨씬 좋게 나와서 submit inference 결과가 잘 이해가 가지 않습니다.. aihub 방언데이터 validation보다 난이도가 훨씬 더 어려운 데이터로 받아들여야할지..

관련하여
1) 방언데이터 평가데이터의 전사문이나 음성데이터에 이상이 없는지 한번만 확인해 주실 수 있으신가요?
2) nsml submit -t 옵션을 넣으면 5개정도의 방언데이터를 inference하는데 이때의 score를 출력하게 해주실 수 있으신가요?
두 질문에 대한 답변 부탁드립니다.

감사합니다.

**Comment by Choiuijin1125** [comment]
안녕하세요. 추가로 문의 드립니다. 
저희팀 같은 경우도 AI Hub 데이터를 다운 받은 후 full-search 기반 validation 을 진행하면 CER 이 평균 10~30 정도로 나오는데요, 
Levenshtein distance 같은 경우, 긴 문장에 대해서는 @aod1310 님께서 언급하신대로 align 하나만 밀려도 스코어가 굉장히 낮게 측정이 될 것 같습니다.

nsml submit -t 를 통해 확인되는 텍스트의 경우도 육안으로 확인 시 CER 값이 0.9 정도는 아니라고 판단되어 지는데, 확인 한 번 부탁드리겠습니다.

문제가 되지 않는다면, nsml submit -t 진행시 나오는 예측 텍스트 값을 참고용으로 업로드하겠습니다.

**Comment by DaconHoneyBee** [comment]
@Choiuijin1125 `nsml submit -t`로 얻은 텍스트값 일부를 좀 보여주실 수 있나요?? 3개 정도 부탁드립니다.

**Comment by Choiuijin1125** [comment]
이미지로 첨부드립니다.

혹시 텍스트로 필요하시면, 메일로 첨부드리겠습니다.

감사합니다.

1. 1번 인덱스
![image](https://user-images.githubusercontent.com/32811094/142155909-cea48cf3-4243-49fd-9dce-63cf184777f5.png)

2. 2번 인덱스
![image](https://user-images.githubusercontent.com/32811094/142155975-f3a593f5-6e59-449e-8c90-e4118a7fdd50.png)

**Comment by DaconHoneyBee** [comment]
@Choiuijin1125 dacon@dacon.io로 텍스트 전달해주시면 감사하겠습니다. 
해당 내용 참고하여 검토 진행하겠습니다. 감사합니다.

**Comment by senti-mkyu** [comment]
@DaconHoneyBee 
저희도 동일한 인덱스의 텍스트를 보내드려도 괜찮을까요?

+ 추가. 21.11.17 17:13
EPD 결과중 앞의 몇 세그먼트만 평가툴에 들어가도록 하였는데 CER이 6.32 (632%) 나옵니다.
제 생각에는 앞의 일부 세그먼트만 인식한 결과를 평가하였기 때문에 뒷부분이 전부 deletion으로 잡힐거고
일부 세그먼트에서 insertion이 아무리 발생했다고 하더라도 전사문의 전체 문자 수를 고려하면 632%까지는 안나오지 않을까싶네요


감사합니다.

**Comment by DaconHoneyBee** [comment]
@aod1310 @Choiuijin1125 보내주신 텍스트로 검증 결과 리더보드에 표시되는 결과보다 훨씬 좋은 점수가 나오는 것을 확인했습니다. 
대신, 채점 과정에서 인덱싱 매치가 잘못되고있는 것으로 파악됐습니다.
문제 파악에 도움 주셔서 감사드리며, 혼란을 드려 죄송합니다.
해당 문제 조치에 대해서 빠른 시간 내로 참가자분들께 연락 및 공지 드리도록 하겠습니다.
죄송합니다.

**Comment by DaconHoneyBee** [comment]
@aod1310 @Choiuijin1125
추가로, stt_3에 적용된 산식(Levenshtein distance 기반)으로 채점시 
align이 밀리더라도 추가적으로 틀린 단어들에 대해서만 에러 카운트가 됩니다.

아래 사진은 보내주신 예측텍스트 중 일부를 사용해서 테스트한 내용입니다.
![image](https://user-images.githubusercontent.com/92906740/142337268-02c2b640-e18a-471c-a1bf-a7565c32623d.png)

**Comment by DaconHoneyBee** [comment]
@aod1310 @Choiuijin1125
추가로, stt_3에 적용된 산식(Levenshtein distance 기반)으로 채점시 
align이 밀리더라도 추가적으로 틀린 단어들에 대해서만 에러 카운트가 됩니다.

아래 사진은 보내주신 예측텍스트 중 일부를 사용해서 테스트한 내용입니다.
![image](https://user-images.githubusercontent.com/92906740/142337502-e45d7812-bea3-49e3-a7d1-51b00a8e0f26.png)

**Comment by Choiuijin1125** [comment]
@DaconHoneyBee 하나 또 배웠네요. 감사합니다.
