### ISSUE TITLE
[NSML] 자체 인프라 활용 문의

### ISSUE THREAD

**Issue by LVCSRer** [hunminjeongeum-competition-final-2021/Speech-to-Text#19]
# 주제
- 자체 인프라 활용하여 훈련한 모델을 NSML 에서 사용하는 일반적인 방식이 있을까요? run 을 실행할때 모델을 포함시키는 방식을 사용하는 경우 전송 가능한 최대 용량이 300MB 로 제한되는 것 같습니다. 이 보다 큰 모델을 사용할 수 있는 방법이 있을까요? 훈련모델 생성시 마다 도커 이미지를 다시 만드는 것은 너무 비효율적인 것 같구요. 확인 부탁드리겠습니다.

# 상황 (자세히 작성해주시면 좋습니다.)
- 

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 사용자 세션 정보: 
- Session ID: 
- 팀명: 
- CLI 에러 (CLI 에러가 아닌 경우 제거)
   ```shell
   # 이곳에 에러 메세지를 넣어주세요
   $ test
   ```

- 웹 UI 에러 이미지
 // 이곳에 에러 이미지를 추가해주세요

# 기타 문의 사항
-

**Comment by senti-mkyu** [comment]
같은 내용을 예선에서 질문드린적 있었는데, 도커 이미지로 빌드해 푸쉬-풀하는 방식으로 진행하라고 하셨습니다

**Comment by LVCSRer** [comment]
> 같은 내용을 예선에서 질문드린적 있었는데, 도커 이미지로 빌드해 푸쉬-풀하는 방식으로 진행하라고 하셨습니다

아 도커 이미지를 사용하는 것이 맞는거군요. 정보 감사드립니다!

**Comment by LVCSRer** [comment]
예선에서 문의 하셨던 내용 확인했습니다. 
https://github.com/hunminjeongeum-korean-competition-2021/voice-recognition/issues/15#issuecomment-944136391

그런데 이 방식이 매우 번거롭게 느껴지는데 300MB 제한을 완화해주시는 것은 어려울까요? @bluebrush

**Comment by DaconHoneyBee** [comment]
@bluebrush 용량 제한 관련하여 답변 주실 수 있을까요?

**Comment by nsmluser** [comment]
@LVCSRer 님, 답변이 늦었습니다. 
먼저, nsml은 nsml 인프라를 전제로 학습 및 submit을 기준으로 개발되었습니다. 
1. CLI를 통한 model upload
2. docker image에 Model을 포함한 방법

CLI를 통한 model Upload 방식의 자체 학습 인프라 제공 방식에 한계가 있습니다. 
보안 등의 목적으로 모든 CLI 데이터를 보존하고 있습니다. 또한 CLI를 통한 동한 동시 upload시 네트워크 상황 등을 고려해야합니다.
그래서, 말씀하신 CLI의 upload크기 상향은 어려운 상황입니다.

**Comment by LVCSRer** [comment]
@nsmluser 네 알겠습니다. 확인 감사합니다.
