### ISSUE TITLE
[NSML] Login server error

### ISSUE THREAD

**Issue by senti-mkyu** [hunminjeongeum-competition-final-2021/Speech-to-Text#2]
# 주제
- nsml 로그인이 안됩니다

# 상황 (자세히 작성해주시면 좋습니다.)
- login failed: login server error

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 사용자 세션 정보:  -
- Session ID: -
- 팀명: UST-LMK
- CLI 에러 (CLI 에러가 아닌 경우 제거)
FATA[2021/11/01 09:17:45.914] login failed: Login server error

- 웹 UI 에러 이미지
![image](https://user-images.githubusercontent.com/19186509/139606248-bcc26540-0761-4cd1-972f-1de5ec4e5ae9.png)

문제
1) nsml 로그인이 안됩니다.
2) nsml 웹사이트에 팀 이름 표기가 안됩니다.
 --> 예선때는 nsml 접속하면 sessions[ust-lmk]로 표시되었는데, 그렇지않네요.

**Comment by bluebrush** [comment]
10시부터 시작입니다.

**Comment by senti-mkyu** [comment]
앗, 메일에 시간이 써있었군요 죄송합니다 ... :)
