### ISSUE TITLE
[대회 진행 관련 문의] 재현성 검증 문의

### ISSUE THREAD

**Issue by senti-mkyu** [hunminjeongeum-competition-final-2021/Speech-to-Text#20]
# 주제
- 재현성 검증 문의

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 리더보드에 올라가있는 세션,모델명이 각팀 Sessions 목록, 모델 목록에 존재하지 않을경우 어떻게되나요? private에 남아있는 record 중 재현되면서 가장 성능 좋은것으로 대체되나요?
- 예시1) nsml세션관리 도중 리더보드에 기록된 session을 삭제 후 다시 훈련하였지만 그 성능에 미치지 못하는경우
- 예시2) 학습 중 'best'라는 이름으로 덮어씌워졌으나 이전 best 성능에 미치지 못함.

대회 운영에 노고가 많으십니다
감사합니다 :)

**Comment by DaconHoneyBee** [comment]
@aod1310 안녕하세요.
삭제하신 최고 점수 session 로그가 남아있는지 NSML 측에 확인 후 답변 드리겠습니다.
감사합니다.

**Comment by senti-mkyu** [comment]
안녕하세요
삭제보다는 모델이 'best'로 덮어씌워졌는데 이전 성능보다 안나오는 경우 어떤 규정으로 처리되고있는지 궁금합니다 :)

감사합니다.

**Comment by DaconHoneyBee** [comment]
@aod1310 기본적으로 리더보드에 올라와 있는 세션을 대상으로 코드 검증을 진행합니다. nia1022/final_stt_3/99/best 모델이 리더보드에 올라와있는데, 99번 세션을 삭제 하셨나요??

**Comment by senti-mkyu** [comment]
@DaconHoneyBee 
아뇨, 문제가 생겼었던쪽은 명령어(final_stt_2)인데, 방금 새로 갱신하여서 문제는 없어졌습니다.
저희도 그렇고 몇몇 팀들이 'best'같은 이름으로 모델 체크포인트를 덮어씌우는 것 처럼 보여서, 혹시 훈련 중에 덮어씌워져서 해당 모델이 유실될경우 어떻게 검증하는지 궁금했습니다..^^;
submit시의 session을 대상으로 검증하신다면 /tmp/~~~~/checkpoint에 리더보드상에 올라가는 모델이 존재할테니 크게 문제되지 않을 것 같아보이네요

답변 감사합니다. 이슈 닫겠습니다 :)
