### ISSUE TITLE
[NSML] 가용 자원이 없다고 합니다

### ISSUE THREAD

**Issue by senti-mkyu** [hunminjeongeum-competition-final-2021/Speech-to-Text#3]
# 주제
- 가용자원이 없다고 합니다.

# 상황 (자세히 작성해주시면 좋습니다.)
- 10시 이후 정상 로그인, baseline을 위해 nsml run 하였으나 가용자원이 없다고 표시됨
- nsml status -rv 하면 gpu 등 사용 가능한 자원이 있다고 표시되고, nsml ps해도 현재 돌아가는 세션이 없음.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
![image](https://user-images.githubusercontent.com/19186509/139609119-49d99be5-4f54-4ccf-a77b-7dbfdff87a7c.png)

- 사용자 세션 정보: 
- Session ID: 
- 팀명: UST-LMK

- 웹 UI 에러 이미지
 ![image](https://user-images.githubusercontent.com/19186509/139609289-d8a8ca16-092b-449b-8120-04b9a896f1c2.png)
웹의 프로필을 눌러보면 가용자원이 전부 0으로 뜨는데 이것과 관련이 있을까요?

# 기타 문의 사항
- 추가로, 예선때 진행했던 session들이 남아있는데, 지워도 상관 없나요?

**Comment by senti-mkyu** [comment]
11시경 웹 UI에 available quota가 정상적으로 출력되는 것을 확인하였습니다.
이에 따라 nsml run 커맨드가 정상적으로 동작하는 것을 확인하였습니다.
태스크당 데이터셋이 늘어남에 따라 prepare dataset... 부분이 좀 걸리긴한데, 계속 기다리면 넘어가네요

**Comment by bluebrush** [comment]
@aod1310  님, 안녕하세요. 
쿼터 설정이 지연되었었습니다. 

예선의 세션은 삭제가능합니다. `nsml rm -f [session-id]`로 진행하시면 됩니다.
혹시, 관리측면에서 일괄 삭제된 이후 명령 실행시 오류 메시지가 있을수 있으나 무시하시면 됩니다.

**Comment by senti-mkyu** [comment]
감사합니다 :)
