### ISSUE TITLE
[NSML] submit 혹은 run 후 동일한 명령어 실행이 가능할 때까지 걸리는 시간이 궁금합니다

### ISSUE THREAD

**Issue by Ldoun** [hunminjeongeum-competition-final-2021/Speech-to-Text#4]
# 주제
- NSML  Since cluster does not have enough computing resources, job has been aborted. Please retry later
- submit 혹은 run 후 다시 시도하기까지 걸리는 시간이 정해져 있나요? 

# 상황 (자세히 작성해주시면 좋습니다.)
- 예전에는 해당 에러가 뜬 뒤 10~20분 정도만 대기하면 다시 run 또는 submit을 할 수 있었는데 지금은 한시간이 넘어가도 동일한 에러를 띄웁니다. 

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 팀명: Ldoun
- CLI 에러 (CLI 에러가 아닌 경우 제거)
   submit 시
   ```shell
   Rejected: not enough resources for your request 
   Since cluster does not have enough computing resources, job has been aborted. Please retry later
   Error: No available machine
   time="2021/11/01 16:13:11.668" level=fatal msg="Internal server error"
   ```
   run 시
  ```shell
  Rejected: not enough resources for your request
  Since cluster does not have enough computing resources, job has been aborted. Please retry later
  Error: No machine available that meets ALL your request such as CPU, RAM, Disk, GPU or its driver version
  time="2021/11/01 16:18:00.131" level=fatal msg="Internal server error" 
  ```

**Comment by Ldoun** [comment]
nsml ps 명령어를 통해 세션 확인도 해보았는데 아직까지 동일한 에러를 띄우면서 실행이 안되네요

**Comment by bluebrush** [comment]
@Ldoun 님, 불편을 드려서 죄송합니다. 
GPU 서버 재 지정되었습니다. 빈 서버라 image pull이 필요할 수 있습니다. 필요한 list 남기시면 image pull 지원해드리겠습니다.

**Comment by Ldoun** [comment]
일단 지금 실행해 보았더니 "......Prepare dataset. It may take a while" 라고 뜨는 것을 보아 실행 될 거 같습니다. 그리고 사용하는 Docker Image는 ldoun8260/nsml:8.0 입니다.

**Comment by bluebrush** [comment]
@Ldoun 님, image pull도 완료되었습니다.

**Comment by Ldoun** [comment]
넵 감사합니다
