### ISSUE TITLE
[Dataset] audio reading 문제와 sox 설치 관련

### ISSUE THREAD

**Issue by kaen2891** [hunminjeongeum-competition-final-2021/Speech-to-Text#6]
# 주제
- 주어진 데이터셋이 읽히지 않는 현상이 발생합니다.

# 상황 (자세히 작성해주시면 좋습니다.)
- 예선전에 사용했던 코드를 그대로 돌리고 있는데 (dataloader 부분), 이번에는 무슨 이유때문인지 모르겠으나 train data가 읽히지 않는 현상 존재합니다. sox 문제인 것 같은데 확인 부탁드려도 되나요?

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- librosa read시 문제
![image](https://user-images.githubusercontent.com/46586785/139647558-4407ae90-afc6-496b-b2fa-3131c1cd412b.png)
backend 문제 발생 (예선전에는 문제 없었음)

- torchaudio 문제
![image](https://user-images.githubusercontent.com/46586785/139647487-d1c34811-9edc-4180-9ed7-26b41bd7df67.png)
여기에서, sox 문제인 것 같아서 sox를 설치하기로 했습니다.

- sox가 없는 것으로 보여서 sox를 nsml_package.txt 에 기입하여서 실행하였는데 아래와 같은 에러 발생
![image](https://user-images.githubusercontent.com/46586785/139674875-9d45c7ec-9295-4ed4-91f3-53e12bb996e5.png)

# 기타 문의 사항
- 예선전에는 이러한 문제가 생기지 않았는데 갑자기 발생하네요. 처리좀 부탁드려도 될까요? @DaconHoneyBee @bluebrush
-

**Comment by kaen2891** [comment]
혹시나하여 ```nsml_package.txt```에 ```yum``` 넣어서 실행 해보아도 같은 에러 발생합니다.

**Comment by Choiuijin1125** [comment]
저도 final_stt1 에서 같은 문제가 발생하네요
final_stt2는 정상적으로 읽어지고 있습니다.
final_stt3는 아직 테스트를 진행해보지 못했습니다.

final_stt1 같은 경우 혹시 몰라 파일을 .wav 로 다시 쓰고 읽어봐도 읽어지지가 않네요.

**Comment by kaen2891** [comment]
@Choiuijin1125 님 말씀처럼 저도 같은 현상인 것 같습니다. ```final_stt_2```에서는 잘 작동하는데 ```final_stt_1```에서는 작동 불가능하니 확인 부탁드립니다. @DaconHoneyBee , @bluebrush

**Comment by senti-mkyu** [comment]
안녕하세요, 해결책은 아니지만 원인은 추정해볼 수 있습니다.
aihub에 업로드된 데이터를 저희쪽에서 데이터 품질 검사하면서 찾은 오류 중에, 음성파일의 헤더자체가 깨져있는 경우가 있습니다.
이 경우 음성파일이 0kb이고, "File contains data in an unknown format." 에러는 재현이 되지만 NoBackendError로 빠지진 않네요. 
다른 오류 유형일 수도 있겠네요..

**Comment by kimkwangho82** [comment]
저도 final_stt_1 에서 같은 현상이 일어납니다. 

![image](https://user-images.githubusercontent.com/1249794/139760424-15bbb0cb-e34a-4020-a0c3-c8de026d001e.png)

* 확인 사항
1. 리눅스 file 명령어시 data 포맷로 나옴 (wav와 다름)
 - 그래서 추정으로는 PCM 형태가 아닌지 궁금하네요 (담당자님께서 확인해 주시면 감사드립니다.)

2. 리눅스 ls -al 명령어로 확인시 데이터  size는 존재함 (저의 경우는 데이터 size가 0이 아닌 경우로 보임)

담당자님께서 확인 및 답변 부탁드립니다.

**Comment by Ldoun** [comment]
문제 해결하셨나요? 저도 동일한 에러가 발생하네요

**Comment by senti-mkyu** [comment]
@Ldoun 안녕하세요
음성파일을 열어서 확인할 수 없어서 찝찝하긴한데
일단 16khz, 16bit pcm으로 읽으시면됩니다.

**Comment by DaconHoneyBee** [comment]
@kaen2891 @Ldoun @aod1310 @kimkwangho82 @Choiuijin1125 안녕하세요.
train_data의 일부 파일들이 PCM 형태로 되어있습니다. 

- PCM 파일: idx0000001 ~ idx0118680
- PCM 샘플링 주파수: 16kHz

확인 및 안내가 늦어 죄송합니다.
