### ISSUE TITLE
[NSML] submit cpu 개수

### ISSUE THREAD

**Issue by LVCSRer** [hunminjeongeum-competition-final-2021/Speech-to-Text#7]
# 주제
- 예선때 7개가 할당되었는데 본선에서는 2개로 진행되는건지 문의드립니다. 

# 상황 (자세히 작성해주시면 좋습니다.)
- 

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 사용자 세션 정보: 
- Session ID: 
- 팀명: 
- CLI 에러 (CLI 에러가 아닌 경우 제거)
   ```shell
   # 이곳에 에러 메세지를 넣어주세요
   $ test
   ```

- 웹 UI 에러 이미지
 // 이곳에 에러 이미지를 추가해주세요

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@LVCSRer 님, 
본선 시작 시점에 공지되지 못한 부분이 죄송합니다. 
현재 2개로 지정되어 있습니다. 아래 수량으로 변경을 검토하고 있습니다. 
[현행]
GPU 1, CPU 2, RAM 60G

[검토중]
GPU 1, CPU 4, RAM 50G

**Comment by kaen2891** [comment]
@bluebrush 님, CPU 4개로 픽스 된 것인지 궁금합니다. 병렬처리 때문에 그러니 알려주시면 감사하겠습니다.
