### ISSUE TITLE
[대회 진행 관련 문의] 상용 STT API 수준

### ISSUE THREAD

**Issue by LVCSRer** [hunminjeongeum-competition-final-2021/Speech-to-Text#9]
# 주제
- 각 참가팀의 경진대회 진행과 직접적으로 관련있는 내용은 아니지만 혹시 본선기간 중 또는 이후라도 google speech-to-text 와 같은 상용 음성인식 API 의 평가 수준도 같이 제시해주실 수 있을까요? 물론 대회에서 타겟을 알고 거기에 최적화 하는 성능과 일반영역을 포괄하는 상용API 와의 직접적인 비교는 크게 의미가 없겠지만 참고는 될 수 있을 것 같고, 추후 홍보에도 활용할 수 있지 않을까 싶어 문의드립니다.

# 상황 (자세히 작성해주시면 좋습니다.)
- 

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 

# 기타 문의 사항
-

**Comment by DaconHoneyBee** [comment]
@LVCSRer 안녕하세요.
운영진 측에서 베이스라인을 포함한 별도의 타 API의 성능은 공개하지 않습니다.
도움 드리지 못해 죄송합니다.

**Comment by LVCSRer** [comment]
네 확인 감사합니다.
